storage_type: data_mapper_storage # pg_database json
max_url_info: 255
per_page_default: 10
time_format: '%d.%m.%Y %H:%M:%S'
geoIP_file: './lib/controler/GeoIP.dat'
json:
  base_dir: './public/reports/'
postgres:
  host: localhost
  port: 5432
  dbname: test_database
  user: seo
  password: seopass
data_mapper:
  database_url: 'postgres://nikolai:nikolai@localhost/test_database'