json:
  base_dir: './spec/export/reports/'
postgres:
  host: localhost
  port: 5432
  dbname: test_database
  user: seo
  password: seopass
data_mapper:
  database_url: 'postgres://nikolai:nikolai@localhost/test_database'